### PR TITLE
Update Json5Parser.cs

### PR DESCRIPTION
**Pull request by tompsono**
Collected Parser some bugs.
Now it can read complex JSON like : "{A:[{},{},],}"
(and System.Collections.Generic.Stack Pushes into FIRST. Caution needed.)

### CODE REVIEW

**Comment by jordanbtucker** [comment]
Thanks for chipping in. Before we start making changes to this project, I think we should replicate the [tests from the beta branch](https://github.com/json5/json5/tree/beta/test) of the reference implementation.

Once we have the tests in place, we can be more confident that the changes we make will be compatible with the reference implementation and [official specification](https://json5.github.io/json5-spec/).

**Comment by jordanbtucker** [comment]
And I'd also like to change this project to use [.NET Standard 2.0](https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md) instead of .NET 4.5.

**Comment by tompsono** [comment]
Yes, my fix may be first-aid, there is a need to review overall.

**Comment by tompsono** [comment]
I think ,  to read ",}" as "}" (or ",]" as "]") on parsing is better solution, if it's possible.
It keeps Parsing algorithm simply.

**Pull request closed without merging**
